import random
import datetime

class FooterManager:
    @staticmethod
    def get_random_quote(theme_config):
        quotes = theme_config.get("quotes", [])
        if not quotes:
            return "Always learning, always building."
        return random.choice(quotes)

    @staticmethod
    def generate_metadata_comment(theme_name, theme_version="1.0"):
        # Current local time in IST (UTC+5:30)
        utc_time = datetime.datetime.now(datetime.timezone.utc)
        ist_time = utc_time + datetime.timedelta(hours=5, minutes=30)
        formatted_time = ist_time.strftime("%Y-%m-%d %H:%M:%S IST")
        
        comment = (
            "<!--\n"
            "Generated by ChronoAI\n"
            f"Theme: {theme_name.capitalize()}\n"
            f"Theme Version: {theme_version}\n"
            f"Generated: {formatted_time}\n"
            "-->"
        )
        return comment
