from __future__ import annotations

import datetime
import random


class FooterManager:
    @staticmethod
    def get_random_quote(theme_config):
        quotes = theme_config.get("quotes", [])
        if not quotes:
            return "Always learning, always building."
        return random.choice(quotes)

    @staticmethod
    def build_footer(context):
        return FooterManager.get_random_quote(context.theme.as_dict())

    @staticmethod
    def generate_metadata_comment(theme_name, theme_version="1.0", timestamp=None):
        # Current local time in IST (UTC+5:30)
        if timestamp is None:
            utc_time = datetime.datetime.now(datetime.timezone.utc)
            timestamp = utc_time + datetime.timedelta(hours=5, minutes=30)

        formatted_time = timestamp.strftime("%Y-%m-%d %H:%M:%S IST")

        comment = (
            "<!--\n"
            "Generated by ChronoAI\n"
            f"Theme: {theme_name.capitalize()}\n"
            f"Theme Version: {theme_version}\n"
            f"Generated: {formatted_time}\n"
            "-->"
        )
        return comment
